server:
  port: 3344

spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tiger7878/microservicecloud-config.git #GitHub上面的Git仓库的名字
